/*******************************************************************************
 * Copyright 2012 Roland Ewald
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package tests.sessl.james

import sessl.util.MiscUtils
import java.io.File
import org.junit.Test
import org.junit.Assert._

/** Tests report creation.
 *  @author Roland Ewald
 */
@Test class TestReport {

  @Test def testReporting() = {

    import sessl._
    import sessl.james._

    val exp = new Experiment with Observation with Report with ParallelExecution {

      model = TestJamesExperiments.testModel
      stopTime = 0.5
      replications = 10
      observe("x" ~ "S0", "y" ~ "S1")
      observeAt(range(0.0, 0.05, 0.5))

      //Some reporting: 
      reportName = "My SESSL Test Report"
      reportDescription = "This was generated by the James II 'Report' trait in Sessl."

      withRunResult {
        results =>
          {
            reportSection("From run " + results.id) {
              linePlot(results.all)(title = "The trajectories of x and y!")
            }
          }
      }

      withExperimentResult {
        results =>
          {
            reportSection("My test section") {
              reportSection("Test-Section sessl-A") {
                scatterPlot(results ~ ("x"), results ~ ("y"))(yLabel = "sessl-label for y-axis", caption = "This is a sessl figure.")
              }
              reportSection("Test-Section sessl-B") {
                histogram(results ~ ("x"))(title = "A fancy histogram.")
                boxPlot(results ~ ("x"), results ~ ("y"))(title = "A boxplot (with named variables)")
                boxPlot(results("x"), results("y"))(title = "Another boxplot (without names)")
                reportStatisticalTest(results ~ ("x"), results ~ ("y"))()
                reportTable(results ~ ("x"), results ~ ("y"))(caption = "This is a table")
              }
            }
          }
      }
    }

    //Best-effort deletion, don't check result (some open programs like R may prevent the deletion of ALL files...)
    MiscUtils.deleteRecursively(exp.reportName)
    val rawDataDir = new File(exp.reportName + "/raw")
    assertFalse("Directory containing raw data should have been deleted.", rawDataDir.exists)

    execute(exp)

    assertTrue("After execution, a directory for raw data should exist.", rawDataDir.exists)
    val files = new File(exp.reportName).list.toSet
    assertTrue("The directory for raw data, the auxiliary plotting methods, and the report itself should be there", files("raw") && files("plotting.R") && files("report.Rtex"))
    val dataFiles = rawDataDir.listFiles
    assertTrue("There should be some files containing the raw data, and none of them should be empty.", dataFiles.length > 0 && dataFiles.forall(_.length > 0))
  }

}
